import { createClient } from '@/lib/supabase/server'
import MissionControlClient from './MissionControlClient'

export const dynamic = 'force-dynamic'

export default async function MissionControlPage() {
  const supabase = await createClient()

  // Fetch all agent runs, sorted by newest first
  const { data: runs } = await supabase
    .from('agent_runs')
    .select('*')
    .order('created_at', { ascending: false })
    .limit(30)

  const latestRunId = runs && runs.length > 0 ? runs[0].id : null

  // Fetch logs for the latest run
  let latestLogs = []
  if (latestRunId) {
    const { data: logs } = await supabase
      .from('agent_logs')
      .select('*')
      .eq('run_id', latestRunId)
      .order('created_at', { ascending: true })
    
    latestLogs = logs || []
  }

  // Fetch outreach contacts generated by Apollo
  const { data: contacts } = await supabase
    .from('outreach_contacts')
    .select('*')
    .order('created_at', { ascending: false })

  return (
    <div className="mission-control-container">
      <MissionControlClient 
        initialRuns={runs || []} 
        initialLogs={latestLogs}
        initialContacts={contacts || []}
      />
    </div>
  )
}
